
version: 2

models:
    - name: accounts_dev_test1
      description: "A starter dbt model"
      columns:
          - name: user_hash
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

